<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>EscalaLixo.Api</RootNamespace>
    <AssemblyName>EscalaLixo.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\supabase\migrations\*.sql" CopyToOutputDirectory="PreserveNewest" Link="supabase\migrations\%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EscalaLixo.Core\EscalaLixo.Core.csproj" />
  </ItemGroup>

</Project>
